### ISSUE TITLE
Jukebox audio output on the host machine

### ISSUE THREAD

**Issue by retro-78** [linuxserver/docker-libresonic#17]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
Hello,

I was wondering if there is a way to use the jukebox function of Libresonic when it's running inside a container and use audio device of the host machine.

I have tried to add `-v /dev/snd:/dev/snd` but it doesn't work.

Your help will be appreciated.

**Comment by CHBMB** [comment]
@retro-78 We do something similar with dvb
```chown -R $PUID:$PGID /dev/snd```  then passthrough to container with ```--device=/dev/snd```

No idea if that will actually work or not though

**Comment by retro-78** [comment]
Hello @CHBMB, I have tried your method without success.

First, I modify user/group of `/dev/snd`
`sudo chown -R root:root /dev/snd/`

Then, I create the container.
```
sudo docker create \
--name="libresonic" \
-v /home/user/libresonic-test/config:/config \
-v /home/user/libresonic-test/music:/music \
-v /home/user/libresonic-test/playlists:/playlists \
-v /home/user/libresonic-test/podcasts:/podcasts \
-v /home/user/libresonic-test/media:/media \
--device=/dev/snd \
-e PGID=0 -e PUID=0 \
-p 4040:4040 \
linuxserver/libresonic
```

Finally, I start the container and I get an error.
`sudo docker start libresonic`
> error gathering device information while adding custom device "/dev/snd": not a device node

Any idea ?

**Comment by tobbenb** [comment]
Which base os are you using?
Which docker version?

**Comment by retro-78** [comment]
Hi @tobbenb,

I am using the 64 bits version of Ubuntu 14.04.
```

$ docker --version
Docker version 1.6.2, build 7c8fca2
```

**Comment by CHBMB** [comment]
Running container as root can cause weird issues.  May want to try running as a non root user.  This is good advice in general not just for this issue @retro-78

**Comment by retro-78** [comment]
Ok @CHBMB thanks for the advice. 

I have added my own user to docker group with 
`sudo usermod -aG docker user`
and then restarted the host machine.

I have tried again the three steps below with my own user and the rights PID and GID but the error still the same.

> Error response from daemon: Cannot start container libresonic: error gathering device information while adding custom device "/dev/snd": not a device node
FATA[0000] Error: failed to start one or more containers

**Comment by tobbenb** [comment]
Using only /dev/snd for the device tag doesn't work in docker versions before 1.7.0. So this means you will have to make a device tag for each of the devices under /dev/snd. Or update to a current docker version...

**Comment by retro-78** [comment]
Thank you @tobbenb and @CHBMB  it's working now !

For those who are interested \:
1) Install the latest version of `docker-ce` package, the installation procedure is described [here](https://store.docker.com/editions/community/docker-ce-server-ubuntu?tab=description).
2) On the host machine change the owner of the device /dev/snd with the command below.
```
$ chown -R $YOURDOCKERUSER:$YOURDOCKEGROUP /dev/snd
```
3) Run docker with a non root user.

- Add $YOURDOCKERUSER to the docker group.
```
$ sudo usermod -aG docker $YOURDOCKERUSER
```
- Restart your host machine.

- After the reboot, the 'docker' group should appear with the command `groups`.
```
$ groups
```
4) Get the user and group id of $YOURDOCKERUSER.

For getting the user id \:
```
$ id -u $YOURDOCKERUSER
```
For getting the group id\:
```
$ id -g $YOURDOCKERGROUP
```
5) Create the container and indicate PID and GID of this user.

```
$ docker create \
--name="libresonic" \
-v </path/to/config>:/config \
-v </path/to/music>:/music \
-v </path/to/playlists>:/playlists \
-v </path/to/podcasts>:/podcasts \
-v </path/to/other media>:/media \
--device=/dev/snd \
-e PGID=<yourdockergroupid> -e PUID=<yourdockeruserid> \
-e CONTEXT_PATH=<url-base> \
-e TZ=<timezone> \
-p 4040:4040 \
linuxserver/libresonic
```
6) Finally, start the container.
```
$ docker start libresonic
```

I close this issue. It could be interesting to propose this parameter in [README.md](https://github.com/linuxserver/docker-libresonic/blob/master/README.md)
