### ISSUE TITLE
transcoding

### ISSUE THREAD

**Issue by ponychicken** [linuxserver/docker-libresonic#18]
Is there something I need to do to enable transcoding? I cant sem to get it to work..

**Comment by retro-78** [comment]
Hi

Transcoding works fine on my side what type of client are you using ?

**Comment by arielelkin** [comment]
@retro-78 I'm having transcoding issues, see here:
https://github.com/Libresonic/libresonic/issues/472

Any thoughts?

**Comment by j0nnymoe** [comment]
From looking at the link referenced. It seems to be an issue with libresonic rather than our container. If I am wrong, please re-open this issue.
