### ISSUE TITLE
Update request to Libresonic 6.2

### ISSUE THREAD

**Issue by retro-78** [linuxserver/docker-libresonic#20]
Hi

Recently Libresonic was updated to version 6.2.
Could you please update the docker image to this version ?

Thanks

**Comment by sparklyballs** [comment]
it's been on version 6.2 since the first friday after it was released back on may 2nd

**Comment by retro-78** [comment]
Ok thanks it is not mentionned in the bottom of the README file. I will pull the new version asap.

**Comment by tobbenb** [comment]
Its not mentioned when it's built during the weekly build as it is automated.
